### ISSUE TITLE
main.py runs extremely slow

### ISSUE THREAD

**Issue by ioneliabuzatu** [ioneliabuzatu/grn-control#16]
https://github.com/ioneliabuzatu/grn-control/blob/main/main.py 

i tried to look up into the self, check for loops or at/set but there is not much i see

**Comment by SimonDufLab** [comment]
If it is only the compilation time, probably we can postpone the investigation for later; since it's not a big setback for research purposes.

What's the total difference in time between running 2/3/4 epochs out of curiosity?

**Comment by ioneliabuzatu** [comment]
_What's the total difference in time between running 2/3/4 epochs out of curiosity?_
very little. a few seconds. Manuel helped with it last week. 

i will close it. for the time being episode/epoch wise is fast. the first episode can be made faster but i agree to inversitgate later
