### ISSUE TITLE
Reproducible simulator

### ISSUE THREAD

**Issue by ioneliabuzatu** [ioneliabuzatu/grn-control#21]
TODO: add fixed seed in jax_simualtor.py

**Comment by ioneliabuzatu** [comment]
the noise in the simulator is reproducible , thank you. 

the noise in technical noise is not tough

**Comment by SimonDufLab** [comment]
Close with [38f2847845119beec33d6ad84874b6d1fee1cc5c](https://github.com/ioneliabuzatu/grn-control/commit/38f2847845119beec33d6ad84874b6d1fee1cc5c)
