### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by manuel-delverme** [ioneliabuzatu/grn-control#4]
```
➜ /tmp git clone git@github.com:ioneliabuzatu/grn-control.git
Cloning into 'grn-control'...
remote: Enumerating objects: 434, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (41/41), done.
Receiving objects:  10% (44/434), 6.72 MiB | 6.60 MiB/s
Receiving objects:  14% (65/434), 19.37 MiB | 924.00 KiB/s 
```
The repo is a bit too big to be cloned.

This commit removed the file from the latest commits but not from the git history.
[ca0f62ee9943878df6b9d4b103f67541e647eff9](https://github.com/ioneliabuzatu/grn-control/commit/ca0f62ee9943878df6b9d4b103f67541e647eff9)

A solution can be found here:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

It should be pretty easy but I have never done it myself.

**Comment by SimonDufLab** [comment]
It worked; you may need to rebase at the next pull though:
`git pull --rebase`
