### ISSUE TITLE
Verification : jnp.(Delta_t) removed : intentional?

### ISSUE THREAD

**Issue by SimonDufLab** [ioneliabuzatu/grn-control#8]
https://github.com/ioneliabuzatu/grn-control/blob/3c286bb52597bb9037e9106717e05abddc610658/jax_simulator.py#L174

Just double check if it is the intended behavior : equation 4 indicates that the Wiener's processes are rescaled by square root of delta_t (I guess that would be the the sampling rate :thinking: )

What is intended to set it to 1?

**Comment by SimonDufLab** [comment]
Hum, I think delta_t is fix later on to 0.01? ;
https://github.com/ioneliabuzatu/grn-control/blob/3c286bb52597bb9037e9106717e05abddc610658/jax_simulator.py#L183

Maybe we should make it a variable

**Comment by ioneliabuzatu** [comment]
it;s in self now. thank you
